name: "Deploy to Hop"
description: "Deploy your project to hop.io using the Hop CLI"
branding:
  color: purple
  icon: cloud
inputs:
  token:
    description: "Personal token for your Hop account"
    required: true
  dir:
    description: "Directory to deploy, defaults to current directory"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy.sh
      shell: bash
      env:
        HOP_TOKEN: ${{ inputs.token }}
        DEPLOY_DIR: ${{ # Grant full read/write access to every possible API scope
permissions: write-all
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
